name: flutter_training
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.4
  flutter: ^3.47.5

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.3
  flutter_svg: ^2.3.0
  yumemi_weather:
    git:
      url: https://github.com/yumemi-inc/flutter-training-template.git
      ref: 5c93099f810c33917e81068e9df537d732ea67be
      path: packages/yumemi_weather

dev_dependencies:
  flutter_test:
    sdk: flutter
  yumemi_lints: ^4.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
